from instance_of_the_world.simulation_objects.dinamic_objects.herbivores import Hearvibore
from instance_of_the_world.simulation_objects.dinamic_objects.predators import Predator
from instance_of_the_world.simulation_objects.static_objects.grass import Grass
from instance_of_the_world.creatures import Creature
from action.selection_of_action import Selection
from action.Coordinates import Coordinates
from maps import Map