from instance_of_the_world.simulation_objects.static_objects.grass import Grass
from instance_of_the_world.simulation_objects.static_objects.trees import Tree
from instance_of_the_world.simulation_objects.static_objects.rocks import Rock